### ISSUE TITLE
Extending to other similar devices (ZY-M100-S_1 and ZY-M100_24GV2)

### ISSUE THREAD

**Issue by jgarridoalcazar** [Andrik45719/ZY-M100#4]
Thank you @Andrik45719 for effort on reducing load for our Zigbee networks.

I wonder if there is any procedure to extend this methodology to other devices. Could you give any clue on how to generate these modified firmware. I also have at home these two models:

- ZY-M100-S_1 (5.8GHz) from _TZE204_sxm7l9xa. [ZY-M100-S_1.zip](https://github.com/user-attachments/files/16946009/ZY-M100-S_1.zip)
- ZY-M100_24GV2 (24GHz) from _TZE204_7gclukjs. [ZY-M100_24GV2.zip](https://github.com/user-attachments/files/16946010/ZY-M100_24GV2.zip)

In case it can be helpful I attach the firmware extracted from these two devices and can upload photos of the interior, if you consider them important.

**Comment by Andrik45719** [comment]
I am disassemble firmware using IDA and search where Tuya DP is sent.
ARM little-endian 
load address 0x8000000 
RAM: 0x20000000-0x20002000

Please upload photos to understand HW differences

**Comment by Andrik45719** [comment]
> * ZY-M100-S_1 (5.8GHz) from _TZE204_sxm7l9xa. [ZY-M100-S_1.zip](https://github.com/user-attachments/files/16946009/ZY-M100-S_1.zip)
> * ZY-M100_24GV2 (24GHz) from _TZE204_7gclukjs. [ZY-M100_24GV2.zip](https://github.com/user-attachments/files/16946010/ZY-M100_24GV2.zip)

[try this and report if OK](https://github.com/Andrik45719/ZY-M100-L/blob/main/ZY-M100-S_1-TargetDistance_disable.bin)

**Comment by jgarridoalcazar** [comment]
Thanks!! After initial tests with the ZY-M100-S_1 version, it seems to be working fine. When presence is false it publishes a burst of 5msgs every minute. I think this is a reasonable amount of traffic for the network.

These are the photos for the ZY-M100-S_1
![2024-09-09-20-53-32-269](https://github.com/user-attachments/assets/b6a3502d-5915-4e19-898f-2145be2ed909)
![2024-09-09-20-52-57-748](https://github.com/user-attachments/assets/43d73817-9d6f-4d13-8a55-4b42e85b7b53)

And these are the photos for the ZY-M100_24GV2
![2024-09-11-11-52-59-855](https://github.com/user-attachments/assets/129481f0-742b-43f1-91e9-b0b538dd0a09)
![2024-09-11-09-26-04-886](https://github.com/user-attachments/assets/fb4b26df-8598-480e-a1bc-1e277f6f6a0e)

**Comment by pimpmytechno** [comment]
Hey guys!
In my case i have Wenzhi ([WZ-M100-W](https://www.zigbee2mqtt.io/devices/WZ-M100-W.html).) Is there any way to obtain modified firmware for this device?

**Comment by Andrik45719** [comment]
> * ZY-M100_24GV2 (24GHz) from _TZE204_7gclukjs. [ZY-M100_24GV2.zip](https://github.com/user-attachments/files/16946010/ZY-M100_24GV2.zip)

Patched FW for 24G uploaded, please check it

**Comment by jgarridoalcazar** [comment]
> > * ZY-M100_24GV2 (24GHz) from _TZE204_7gclukjs. [ZY-M100_24GV2.zip](https://github.com/user-attachments/files/16946010/ZY-M100_24GV2.zip)
> 
> Patched FW for 24G uploaded, please check it

Initial testing and working as expected. When presence=true, it reports one message every 30 seconds. When presence=false, once every 10 seconds.

Thanks again for finding this solution for a general issue of Zigbee Tuya presence sensors.

**Comment by pimpmytechno** [comment]
> > * ZY-M100_24GV2 (24GHz) from _TZE204_7gclukjs. [ZY-M100_24GV2.zip](https://github.com/user-attachments/files/16946010/ZY-M100_24GV2.zip)
> 
> Patched FW for 24G uploaded, please check it

Can you please generate firmware for _TZE204_e5m9c5hl 
[TZE204_e5m9c5hl.zip](https://github.com/user-attachments/files/17018362/TZE204_e5m9c5hl.zip)

**Comment by Andrik45719** [comment]
> > > * ZY-M100_24GV2 (24GHz) from _TZE204_7gclukjs. [ZY-M100_24GV2.zip](https://github.com/user-attachments/files/16946010/ZY-M100_24GV2.zip)
> > 
> > 
> > Patched FW for 24G uploaded, please check it
> 
> Can you please generate firmware for _TZE204_e5m9c5hl? [TZE204_e5m9c5hl.zip](https://github.com/user-attachments/files/17018362/TZE204_e5m9c5hl.zip)

You can flash [_TZE204_sxm7l9xa](https://github.com/Andrik45719/ZY-M100/blob/main/ZY-M100-S_1_TZE204_sxm7l9xa-TargetDistance_disable.bin)
The firmware differs only in the 'Zigbee Manufacturer' code.

**Comment by jgarridoalcazar** [comment]
After testing during dinner time they are working as expected.

**Comment by djcrawleravp** [comment]
Is the WZ-M100 (_TZE204_laokfqwu) incompatible and impossible to flash, or is there a chance it could be supported in the future? That's my only sensor left :/
