### ISSUE TITLE
_TZE204_ya4ft0w4 support

### ISSUE THREAD

**Issue by bsaurusrex** [Andrik45719/ZY-M100#7]
BIN:
[ZY-M100_bkup_v3.zip](https://github.com/user-attachments/files/17188825/ZY-M100_bkup_v3.zip)

Model: ZY-M100-24GV3

![IMG_0048](https://github.com/user-attachments/assets/d6b9dfa2-737f-4769-831b-e90b11437279)
![IMG_0049](https://github.com/user-attachments/assets/6a8d3987-c8da-480c-9d4f-6a1dcfbc449b)

**Comment by bsaurusrex** [comment]
Not necessary.

https://github.com/Koenkk/zigbee-herdsman-converters/pull/7909

**Comment by thargy** [comment]
Hi @bsaurusrex,

I've completed extensive testing with 26_TZE204_ya4ft0w4devices, and tried one of the newer `_TZE204_ya4ft0w4`.

Frankly the older `_TZE204_ya4ft0w4` devices with your firmware were _significantly_ better than the newer `_TZE204_ya4ft0w4` - which was still way too chatty (even with the distance reporting switched off) - and I also found the presence detection on the newer devices to be way less reliable!

Your firmware tweaks to the various timeouts makes a _massive_ difference, and similar tweaks to the `_TZE204_ya4ft0w4` would probably improve it too.

**Comment by Andrik45719** [comment]
[ZY-M100-24GV3_TZE204_ya4ft0w4_increased_report_interval](https://github.com/Andrik45719/ZY-M100/blob/main/ZY-M100-24GV3_TZE204_ya4ft0w4_increased_report_interval.bin)

**Comment by 8none1** [comment]
I bought a  _TZE204_ya4ft0w4 device which already had the distance switch firmware and it was still way too chatty.  I applied the [ZY-M100-24GV3_TZE204_ya4ft0w4_increased_report_interval_TD_0_disable.bin](https://github.com/Andrik45719/ZY-M100/blob/main/ZY-M100-24GV3_TZE204_ya4ft0w4_increased_report_interval_TD_0_disable.bin) and it is now much much better. 

Thank you!

@thargy I had a device which was identical to this one, in case that helps you:  https://github.com/Koenkk/zigbee2mqtt/issues/19045#issuecomment-2415435611

@Andrik45719 do you have a kofi or something so I can buy you a beer?
